# Generated by Django 3.1 on 2020-10-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorServices',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=20)),
                ('description', models.TextField(default='', max_length=200)),
                ('service_is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Vendor Services',
            },
        ),
    ]
