# Generated by Django 3.1 on 2020-10-16 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20201016_1033'),
        ('restapi', '0002_vendorvideos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorServices',
        ),
        migrations.DeleteModel(
            name='VendorVideos',
        ),
    ]
