# Generated by Django 3.1 on 2020-11-07 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('Address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('EmailID', models.CharField(blank=True, max_length=50, null=True)),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('extra_Info', models.TextField(blank=True, max_length=200, null=True)),
                ('Contact_Person', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('customer_is_active', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.branch')),
                ('subscription_plan_taken', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.plan')),
            ],
            options={
                'ordering': ['customer_id'],
            },
        ),
    ]
