# Generated by Django 3.1 on 2020-10-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_auto_20201019_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
        migrations.AlterField(
            model_name='customer',
            name='EmailID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
