# Generated by Django 3.1 on 2020-10-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_auto_20201020_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['customer_id']},
        ),
    ]
