# Generated by Django 3.1 on 2020-10-29 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20201029_1907'),
        ('Customer', '0007_auto_20201023_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.branch'),
        ),
    ]
