# Generated by Django 3.1 on 2020-10-13 07:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTestimonial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(default='', max_length=50)),
                ('quote', models.TextField(default='', max_length=350)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(default='', max_length=50)),
                ('Image', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])])),
                ('category_description', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('category_is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_category', models.CharField(default='', max_length=100)),
                ('market_executive_name', models.CharField(default='', max_length=50)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('feed_back', models.CharField(default=False, max_length=50)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('Comments', models.TextField()),
                ('customer_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='FreeListing',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('Company_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.IntegerField()),
                ('mobile', models.BigIntegerField()),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Vendor Requests',
            },
        ),
        migrations.CreateModel(
            name='FrenchiseContact',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.CharField(default='', max_length=200)),
                ('frenchise_option', models.CharField(default='', max_length=50)),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('seeker_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('education', models.CharField(default='', max_length=200)),
                ('experience', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('email_id', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=20)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.CharField(max_length=111)),
                ('state', models.CharField(choices=[('1', 'Please Select'), ('2', 'Andra Pradesh'), ('3', 'Arunachal Pradesh'), ('4', 'Assam'), ('5', 'Bihar'), ('6', 'Chhattisgarh'), ('7', 'Chandigarh'), ('8', 'Dadar and Nagar Haveli'), ('9', 'Daman and Diu'), ('10', 'Delhi'), ('11', 'Goa'), ('12', 'Gujarat'), ('13', 'Haryana'), ('14', 'Himachal Pradesh'), ('15', 'Jammu and Kashmir'), ('16', 'Jharkhand'), ('17', 'Karnataka'), ('18', 'Kerala'), ('19', 'Lakshadeep'), ('20', 'Madya Pradesh'), ('21', 'Maharashtra'), ('22', 'Manipur'), ('23', 'Meghalaya'), ('24', 'Mizoram'), ('25', 'Nagaland'), ('26', 'Orissa'), ('27', 'Punjab'), ('28', 'Pondicherry'), ('29', 'Rajasthan'), ('30', 'Sikkim'), ('31', 'Tamil Nadu'), ('32', 'Telagana'), ('33', 'Tripura'), ('34', 'Uttaranchal'), ('35', 'Uttar Pradesh'), ('36', 'West Bengal'), ('37', 'Andaman and Nicobar Island')], max_length=111)),
                ('city', models.CharField(max_length=111)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('zip_code', models.CharField(max_length=8)),
                ('amount', models.IntegerField()),
                ('order_completed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=25)),
                ('plan_amount', models.IntegerField()),
                ('minimum_discount', models.IntegerField()),
                ('maximum_discount', models.IntegerField()),
                ('description_1', models.CharField(max_length=50, null=True)),
                ('description_2', models.CharField(max_length=50, null=True)),
                ('description_3', models.CharField(max_length=50, null=True)),
                ('description_4', models.CharField(max_length=50, null=True)),
                ('plan_img', models.ImageField(default='', upload_to='website/membershipcard')),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=27)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QueryContact',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceContact',
            fields=[
                ('registrant_id', models.AutoField(primary_key=True, serialize=False)),
                ('registrant_name', models.CharField(default='', max_length=50)),
                ('registrant_mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('registrant_interest', models.CharField(default='', max_length=50)),
                ('registrant_query', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trading',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('address_from', models.CharField(max_length=50)),
                ('address_to', models.CharField(max_length=50)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('zip_code', models.IntegerField(default='')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Upload_resume',
            fields=[
                ('resume_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('filling_date', models.DateTimeField(auto_now_add=True)),
                ('Resume', models.FileField(blank=True, null=True, upload_to='website/JobResumes', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'word'])])),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=50)),
                ('Company_Name', models.CharField(default='', max_length=100)),
                ('Service_decsription', models.TextField(default='', max_length=1000)),
                ('Mobile_No', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Mobile_No_2', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Address1', models.CharField(default='', max_length=100)),
                ('Address2', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(choices=[('1', 'Please Select'), ('2', 'Andra Pradesh'), ('3', 'Arunachal Pradesh'), ('4', 'Assam'), ('5', 'Bihar'), ('6', 'Chhattisgarh'), ('7', 'Chandigarh'), ('8', 'Dadar and Nagar Haveli'), ('9', 'Daman and Diu'), ('10', 'Delhi'), ('11', 'Goa'), ('12', 'Gujarat'), ('13', 'Haryana'), ('14', 'Himachal Pradesh'), ('15', 'Jammu and Kashmir'), ('16', 'Jharkhand'), ('17', 'Karnataka'), ('18', 'Kerala'), ('19', 'Lakshadeep'), ('20', 'Madya Pradesh'), ('21', 'Maharashtra'), ('22', 'Manipur'), ('23', 'Meghalaya'), ('24', 'Mizoram'), ('25', 'Nagaland'), ('26', 'Orissa'), ('27', 'Punjab'), ('28', 'Pondicherry'), ('29', 'Rajasthan'), ('30', 'Sikkim'), ('31', 'Tamil Nadu'), ('32', 'Telagana'), ('33', 'Tripura'), ('34', 'Uttaranchal'), ('35', 'Uttar Pradesh'), ('36', 'West Bengal'), ('37', 'Andaman and Nicobar Island')], default='Please Select', max_length=100)),
                ('PinCode', models.IntegerField()),
                ('Contact_Person', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('EmailID', models.EmailField(blank=True, max_length=254, null=True)),
                ('Landline', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('GST_No', models.IntegerField(blank=True, null=True)),
                ('Pan_No', models.IntegerField(blank=True, null=True)),
                ('TIN_No', models.IntegerField(blank=True, null=True)),
                ('Registered_Trade_Name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Facebook_URL', models.URLField(blank=True, null=True)),
                ('Twitter_URL', models.URLField(blank=True, null=True)),
                ('website_URL', models.URLField(blank=True, null=True)),
                ('Status', models.CharField(choices=[('1', 'Please Select'), ('2', 'New'), ('3', 'Verified')], default='New', max_length=20)),
                ('Other_Info', models.CharField(blank=True, max_length=200, null=True)),
                ('Discount_Percentage', models.IntegerField(null=True)),
                ('Longitude', models.FloatField(blank=True, null=True)),
                ('Latitude', models.FloatField(blank=True, null=True)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('Image', models.ImageField(default='', upload_to='website/images/vendors')),
                ('Busniess_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='website.categories')),
                ('vendor_services', models.ManyToManyField(to='restapi.VendorServices')),
            ],
        ),
        migrations.CreateModel(
            name='TOP',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(default='', max_length=50)),
                ('vendor_work_desc', models.TextField(default='', max_length=1000)),
                ('address', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('vendor_mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('vendor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Image', models.ImageField(default='', upload_to='website/images/TOPvendors')),
                ('Busniess_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('subcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_category_name', models.CharField(default='', max_length=50)),
                ('category_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='website.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_sub_category',
            fields=[
                ('subcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_sub_category_name', models.CharField(default='', max_length=50)),
                ('sub_category_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='website.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50)),
                ('category_title', models.CharField(default='', max_length=150)),
                ('price', models.IntegerField(default=0)),
                ('service_desc', models.TextField(default='', max_length=200)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('Image', models.ImageField(default='', upload_to='website/images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.categories')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fathers_name', models.CharField(blank=True, max_length=50)),
                ('Mobile_No', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Mobile_No_2', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Address', models.CharField(default='', max_length=100)),
                ('City', models.CharField(default='', max_length=100)),
                ('State', models.CharField(choices=[('1', 'Please Select'), ('2', 'Andra Pradesh'), ('3', 'Arunachal Pradesh'), ('4', 'Assam'), ('5', 'Bihar'), ('6', 'Chhattisgarh'), ('7', 'Chandigarh'), ('8', 'Dadar and Nagar Haveli'), ('9', 'Daman and Diu'), ('10', 'Delhi'), ('11', 'Goa'), ('12', 'Gujarat'), ('13', 'Haryana'), ('14', 'Himachal Pradesh'), ('15', 'Jammu and Kashmir'), ('16', 'Jharkhand'), ('17', 'Karnataka'), ('18', 'Kerala'), ('19', 'Lakshadeep'), ('20', 'Madya Pradesh'), ('21', 'Maharashtra'), ('22', 'Manipur'), ('23', 'Meghalaya'), ('24', 'Mizoram'), ('25', 'Nagaland'), ('26', 'Orissa'), ('27', 'Punjab'), ('28', 'Pondicherry'), ('29', 'Rajasthan'), ('30', 'Sikkim'), ('31', 'Tamil Nadu'), ('32', 'Telagana'), ('33', 'Tripura'), ('34', 'Uttaranchal'), ('35', 'Uttar Pradesh'), ('36', 'West Bengal'), ('37', 'Andaman and Nicobar Island')], default='Please Select', max_length=100)),
                ('PinCode', models.IntegerField()),
                ('Gross_Salary', models.IntegerField()),
                ('Gender', models.CharField(choices=[('1', 'Please Select'), ('2', 'Male'), ('3', 'Female'), ('4', 'Other')], default='Please Select', max_length=100)),
                ('Date_of_Birth', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=8)),
                ('gateway_name', models.CharField(max_length=25)),
                ('response_message', models.TextField()),
                ('bank_name', models.CharField(max_length=25)),
                ('Payment_mode', models.CharField(max_length=25)),
                ('response_code', models.CharField(max_length=3)),
                ('txn_id', models.TextField()),
                ('txn_amount', models.CharField(max_length=9)),
                ('order_id', models.IntegerField()),
                ('status', models.CharField(max_length=12)),
                ('bank_txn_id', models.CharField(max_length=12)),
                ('txn_date', models.CharField(max_length=23)),
                ('refund_amount', models.IntegerField(default=0.0)),
                ('order_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='plan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.plan'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Contactviacategory',
            fields=[
                ('registrant_id', models.AutoField(primary_key=True, serialize=False)),
                ('registrant_name', models.CharField(default='', max_length=50)),
                ('registrant_mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('calling_time', models.CharField(default='', max_length=50)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('service_name', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.subcategory')),
                ('sub_service_name', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.sub_sub_category')),
            ],
        ),
    ]
