# Generated by Django 3.0.8 on 2020-08-25 18:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_category', models.CharField(default='', max_length=100)),
                ('market_executive_name', models.CharField(default='', max_length=50)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('feed_back', models.CharField(default=False, max_length=50)),
                ('Comments', models.TextField()),
                ('customer_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='FreeListing',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('Company_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.IntegerField(default='')),
                ('mobile', models.IntegerField(default='')),
                ('email', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('seeker_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default='')),
                ('education', models.CharField(default='', max_length=200)),
                ('experience', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=25)),
                ('plan_amount', models.IntegerField()),
                ('description_1', models.CharField(max_length=50, null=True)),
                ('description_2', models.CharField(max_length=50, null=True)),
                ('description_3', models.CharField(max_length=50, null=True)),
                ('description_4', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueryContacts',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=150)),
                ('category_title', models.CharField(default='', max_length=150)),
                ('subcategory', models.CharField(default='', max_length=150)),
                ('price', models.IntegerField(default=0)),
                ('service_desc', models.CharField(max_length=120)),
                ('publish_date', models.DateField()),
                ('Image', models.ImageField(default='', upload_to='website/images')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceContact',
            fields=[
                ('registrant_id', models.AutoField(primary_key=True, serialize=False)),
                ('registrant_name', models.CharField(default='', max_length=50)),
                ('registrant_mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('registrant_interest', models.CharField(default='', max_length=50)),
                ('registrant_query', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TOP',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(default='', max_length=50)),
                ('Busniess_Type', models.CharField(default='', max_length=100)),
                ('vendor_work_desc', models.TextField(default='', max_length=1000)),
                ('address', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('vendor_mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('vendor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Image', models.ImageField(default='', upload_to='website/images/TOPvendors')),
            ],
        ),
        migrations.CreateModel(
            name='Trading',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('address_from', models.CharField(max_length=50)),
                ('address_to', models.CharField(max_length=50)),
                ('zip_code', models.IntegerField(default='')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Upload_resume',
            fields=[
                ('resume_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('Resume', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'word'])])),
            ],
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=50)),
                ('Company_Name', models.CharField(default='', max_length=100)),
                ('Service_decsription', models.CharField(default='', max_length=1000)),
                ('Mobile_No', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Mobile_No_2', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Address1', models.CharField(default='', max_length=100)),
                ('Address2', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(choices=[('1', 'Please Select'), ('2', 'Andra Pradesh'), ('3', 'Arunachal Pradesh'), ('4', 'Assam'), ('5', 'Bihar'), ('6', 'Chhattisgarh'), ('7', 'Chandigarh'), ('8', 'Dadar and Nagar Haveli'), ('9', 'Daman and Diu'), ('10', 'Delhi'), ('11', 'Goa'), ('12', 'Gujarat'), ('13', 'Haryana'), ('14', 'Himachal Pradesh'), ('15', 'Jammu and Kashmir'), ('16', 'Jharkhand'), ('17', 'Karnataka'), ('18', 'Kerala'), ('19', 'Lakshadeep'), ('20', 'Madya Pradesh'), ('21', 'Maharashtra'), ('22', 'Manipur'), ('23', 'Meghalaya'), ('24', 'Mizoram'), ('25', 'Nagaland'), ('26', 'Orissa'), ('27', 'Punjab'), ('28', 'Pondicherry'), ('29', 'Rajasthan'), ('30', 'Sikkim'), ('31', 'Tamil Nadu'), ('32', 'Telagana'), ('33', 'Tripura'), ('34', 'Uttaranchal'), ('35', 'Uttar Pradesh'), ('36', 'West Bengal'), ('37', 'Andaman and Nicobar Island')], default='Please Select', max_length=100)),
                ('Contact_Person', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('EmailID', models.EmailField(blank=True, max_length=254, null=True)),
                ('Landline', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('GST_No', models.IntegerField(blank=True, null=True)),
                ('Pan_No', models.IntegerField(blank=True, null=True)),
                ('TIN_No', models.IntegerField(blank=True, null=True)),
                ('Registered_Trade_Name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Facebook_URL', models.URLField(blank=True, null=True)),
                ('Twitter_URL', models.URLField(blank=True, null=True)),
                ('website_URL', models.URLField(blank=True, null=True)),
                ('Status', models.CharField(choices=[('1', 'Please Select'), ('2', 'New'), ('3', 'Verified')], default='New', max_length=20)),
                ('Other_Info', models.CharField(blank=True, max_length=200, null=True)),
                ('Discount_Percentage', models.IntegerField(null=True)),
                ('Longitude', models.FloatField(blank=True, null=True)),
                ('Latitude', models.FloatField(blank=True, null=True)),
                ('Image', models.ImageField(default='', upload_to='website/images/vendors')),
                ('Busniess_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='website.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('subcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_category_name', models.CharField(default='', max_length=50)),
                ('category_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='website.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_sub_category',
            fields=[
                ('subcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_sub_category_name', models.CharField(default='', max_length=50)),
                ('sub_category_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='website.Subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('email_id', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=111)),
                ('state', models.CharField(max_length=111)),
                ('city', models.CharField(max_length=111)),
                ('zip_code', models.CharField(max_length=8)),
                ('payment_status', models.CharField(max_length=8)),
                ('amount', models.IntegerField()),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Plans')),
            ],
        ),
        migrations.CreateModel(
            name='Contactviacategory',
            fields=[
                ('registrant_id', models.AutoField(primary_key=True, serialize=False)),
                ('registrant_name', models.CharField(default='', max_length=50)),
                ('registrant_mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('calling_time', models.CharField(default='', max_length=50)),
                ('service_name', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Subcategory')),
                ('sub_service_name', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Sub_sub_category')),
            ],
        ),
    ]
