# Generated by Django 3.1 on 2020-11-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactviacategory',
            name='registrant_mobile_no',
            field=models.CharField(blank=True, default='', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='querycontact',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='servicecontact',
            name='registrant_mobile_no',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='top',
            name='vendor_mobile_no',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trading',
            name='mobile',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
