# Generated by Django 3.0.8 on 2020-08-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='Image',
            field=models.ImageField(default='', upload_to='website/images/categories'),
        ),
    ]
