# Generated by Django 3.1 on 2020-10-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='top',
            name='app_exists',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='top',
            name='app_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
