# Generated by Django 3.0.7 on 2020-09-07 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('email_id', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=111)),
                ('state', models.CharField(max_length=111)),
                ('city', models.CharField(max_length=111)),
                ('zip_code', models.CharField(max_length=8)),
                ('amount', models.IntegerField()),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='order_payment',
            name='order_summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Order2'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
