# Generated by Django 3.0.7 on 2020-09-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_payment',
            name='order_completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
