# Generated by Django 3.0.8 on 2020-08-25 23:56

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrenchiseContacts',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.CharField(default='', max_length=200)),
                ('frenchise_option', models.CharField(default='', max_length=50)),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
