# Generated by Django 3.0.8 on 2020-08-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('seeker_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default='')),
                ('email', models.CharField(default='', max_length=50)),
                ('experience', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
