# Generated by Django 3.1 on 2020-10-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201020_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top',
            name='app_exists',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], default=False, max_length=20, null=True),
        ),
    ]
