# Generated by Django 3.0.8 on 2020-08-30 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_categories_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='Image',
            field=models.ImageField(default='', upload_to='website/images/categories', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
