# Generated by Django 3.0.8 on 2020-08-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Resume',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
    ]
