# Generated by Django 3.0.8 on 2020-08-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_frenchisecontacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FrenchiseContacts',
            new_name='FrenchiseContact',
        ),
        migrations.RenameModel(
            old_name='Plans',
            new_name='Plan',
        ),
        migrations.RenameModel(
            old_name='QueryContacts',
            new_name='QueryContact',
        ),
        migrations.RenameModel(
            old_name='Vendors',
            new_name='Vendor',
        ),
    ]
