# Generated by Django 3.1 on 2020-10-13 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_vendorvideos'),
        ('website', '0002_auto_20201013_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.vendorvideos'),
        ),
    ]
