# Generated by Django 3.1 on 2020-10-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20201020_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top',
            name='app_exists',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='top',
            name='app_url',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
