# Generated by Django 3.0.7 on 2020-09-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200910_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_payment',
            name='response_message',
            field=models.TextField(),
        ),
    ]
