# Generated by Django 3.0.8 on 2020-08-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200808_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Resume',
            field=models.FileField(default='', upload_to='website/documents'),
        ),
        migrations.AlterField(
            model_name='service',
            name='Image',
            field=models.ImageField(default='', upload_to='website/images'),
        ),
    ]
