# Generated by Django 3.1 on 2020-10-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_vendor_vendor_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='business_history_with_sbt',
            field=models.CharField(choices=[('none', 'Please Select'), ('YES', 'YES'), ('NO', 'NO')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='geograpgical_area',
            field=models.CharField(choices=[('none', 'Please Select'), ('village', 'Village'), ('district', 'District'), ('tehsil', 'Tehsil'), ('state', 'State')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='registration_fee',
            field=models.CharField(choices=[('none', 'Please Select'), ('INR 1200/per month', 'INR 1200/per month'), ('INR 12000/per yearly', 'INR 12000/per yearly'), ('Registration Fee(INR 100@ lifetime)', 'Registration Fee(INR 100@ lifetime)'), ('Sbt marketing concept', 'Sbt marketing concept')], default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='type_of_commodity_or_business',
            field=models.CharField(choices=[('none', 'Please Select'), ('consultant', 'Consultant'), ('distrubution', 'Distrubution'), ('service provider', 'Service Provider'), ('freght/transportation', 'Freght/Transportation'), ('authorised agent', 'Authorised Agent'), ('trader', 'Trader'), ('trader', 'Other')], default='service provider', max_length=100),
        ),
    ]
