# Generated by Django 3.0.8 on 2020-08-30 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200830_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])]),
        ),
    ]
