# Generated by Django 3.0.8 on 2020-08-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200808_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Resume',
            field=models.FileField(upload_to=''),
        ),
    ]
