# Generated by Django 3.0.8 on 2020-08-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200830_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTestimonial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(default='', max_length=50)),
                ('quote', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
