# Generated by Django 3.1 on 2020-10-13 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20201013_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='website.categories'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subchilren', to='website.subcategory'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='Busniess_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorY', to='website.categories'),
        ),
        migrations.AlterUniqueTogether(
            name='categories',
            unique_together={('parent', 'category_name')},
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('parent', 'sub_category_name')},
        ),
    ]
