# Generated by Django 3.0.8 on 2020-08-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_addtestimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtestimonial',
            name='quote',
            field=models.TextField(default='', max_length=200),
        ),
    ]
