# Generated by Django 3.1 on 2020-10-13 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20201013_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.subcategory'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='Busniess_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='website.categories'),
        ),
    ]
