# Generated by Django 3.0.8 on 2020-08-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200826_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelisting',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
