# Generated by Django 3.1 on 2020-09-19 05:18

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200912_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='upload_resume',
            name='Resume',
            field=models.FileField(blank=True, null=True, upload_to='website/JobResumes', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'word'])]),
        ),
    ]
