# Generated by Django 3.1 on 2020-10-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20201020_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top',
            name='app_url',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
