# Generated by Django 3.0.8 on 2020-08-08 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200808_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 16, 3, 10, 435022)),
        ),
    ]
