# Generated by Django 3.0.8 on 2020-08-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200830_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtestimonial',
            name='quote',
            field=models.TextField(default='', max_length=250),
        ),
    ]
