# Generated by Django 3.1 on 2020-10-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20201013_1745'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categories',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='categories',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='parent',
        ),
    ]
