# Generated by Django 3.0.8 on 2020-08-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_job_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='publish_date',
            field=models.DateField(),
        ),
    ]
