# Generated by Django 3.0.8 on 2020-08-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200830_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtestimonial',
            name='quote',
            field=models.TextField(default='', max_length=350),
        ),
    ]
