# Generated by Django 3.0.8 on 2020-08-26 15:28

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200826_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelisting',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
