# Generated by Django 3.1 on 2020-09-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200919_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='maximum_discount',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='minimum_discount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
