# Generated by Django 3.0.8 on 2020-08-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200808_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Resume',
            field=models.FileField(blank=True, null=True, upload_to='website/static/resumes'),
        ),
    ]
