# Generated by Django 3.1 on 2020-10-13 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20201013_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.subcategory'),
        ),
    ]
