# Generated by Django 3.0.8 on 2020-08-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200826_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelisting',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='freelisting',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
