# Generated by Django 3.1 on 2020-10-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20201020_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frenchisecontact',
            options={'verbose_name_plural': 'Frenchise Requests'},
        ),
        migrations.AddField(
            model_name='frenchisecontact',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='frenchisecontact',
            name='message',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
