# Generated by Django 3.1 on 2020-09-30 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200923_1411'),
        ('website', '0006_auto_20200912_1742'),
    ]

    operations = [
    ]
