# Generated by Django 3.1 on 2020-10-22 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20201020_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
