# Generated by Django 3.0.8 on 2020-08-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200826_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
