# Generated by Django 3.1 on 2020-10-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20201013_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='subcategory',
        ),
    ]
