# Generated by Django 3.1 on 2020-10-06 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_plan_plan_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freelisting',
            options={'verbose_name_plural': 'Vendor Requests'},
        ),
    ]
