# Generated by Django 3.0.8 on 2020-08-08 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200808_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='publish_date',
            new_name='filling_date',
        ),
    ]
