# Generated by Django 3.0.8 on 2020-08-08 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20200808_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='filling_date',
        ),
    ]
