# Generated by Django 3.1.2 on 2020-10-14 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_customer'),
        ('website', '0011_remove_vendor_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.employee'),
        ),
    ]
