# Generated by Django 3.0.8 on 2020-08-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20200826_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='PinCode',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
