# Generated by Django 3.0.8 on 2020-08-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_remove_job_filling_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_resume',
            fields=[
                ('resume_id', models.AutoField(primary_key=True, serialize=False)),
                ('filling_date', models.DateField()),
                ('Resume', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='Resume',
        ),
    ]
