# Generated by Django 3.1 on 2020-10-23 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_order_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frenchisecontact',
            old_name='frenchise_option',
            new_name='franchise_option',
        ),
    ]
