# Generated by Django 3.0.8 on 2020-08-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_vendor_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
