# Generated by Django 3.0.8 on 2020-08-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20200808_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_resume',
            name='filling_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
