# Generated by Django 3.1 on 2020-10-23 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20201023_0856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['category_name']},
        ),
    ]
