# Generated by Django 3.0.8 on 2020-08-26 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20200826_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='date_created',
        ),
    ]
