# Generated by Django 3.1 on 2020-10-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20201023_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='website/membershipcard'),
        ),
    ]
