# Generated by Django 3.0.8 on 2020-08-08 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20200808_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_resume',
            name='filling_date',
        ),
    ]
