# Generated by Django 3.0.8 on 2020-08-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_remove_upload_resume_filling_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_resume',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
