# Generated by Django 3.0.8 on 2020-08-08 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_upload_resume_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_resume',
            name='Resume',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'word'])]),
        ),
    ]
