# Generated by Django 3.1 on 2020-11-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
