# Generated by Django 3.0.8 on 2020-08-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Fathers_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
