# Generated by Django 3.1 on 2020-11-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_order_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
