# Generated by Django 3.0.8 on 2020-08-08 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_job_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='email',
        ),
    ]
