# Generated by Django 3.0.8 on 2020-08-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20200828_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_desc',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
