# Generated by Django 3.0.8 on 2020-08-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='sub_category_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
