# Generated by Django 3.0.8 on 2020-08-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_categories_sub_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='sub_category_name',
            new_name='sub_category_name1',
        ),
        migrations.AddField(
            model_name='categories',
            name='sub_category_name10',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='categories',
            name='sub_category_name2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='categories',
            name='sub_category_name3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='categories',
            name='sub_category_name4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='categories',
            name='sub_category_name5',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='categories',
            name='sub_category_name6',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='categories',
            name='sub_category_name7',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='categories',
            name='sub_category_name8',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='categories',
            name='sub_category_name9',
            field=models.CharField(default='', max_length=50),
        ),
    ]
