# Generated by Django 3.0.8 on 2020-08-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20200828_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='Service_decsription',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
