# Generated by Django 3.0.8 on 2020-08-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20200810_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='sub_category_name1',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='sub_category_name10',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='sub_category_name2',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='sub_category_name3',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='sub_category_name4',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='sub_category_name5',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='sub_category_name6',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='sub_category_name7',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='sub_category_name8',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='sub_category_name9',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
