# Generated by Django 3.0.8 on 2020-08-11 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20200810_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='response_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='response_msg',
        ),
    ]
