# Generated by Django 3.0.8 on 2020-08-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20200828_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_desc',
            field=models.TextField(default='', max_length=200),
        ),
    ]
