# Generated by Django 3.0.8 on 2020-08-28 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20200828_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top',
            name='Busniess_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Categories'),
        ),
    ]
