# Generated by Django 3.0.8 on 2020-08-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20200812_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_desc',
            field=models.CharField(max_length=120),
        ),
    ]
