# Generated by Django 3.0.8 on 2020-08-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20200812_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOP',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(default='', max_length=50)),
                ('vendor_work_desc', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('vendor_mobile_no', models.IntegerField(max_length=13)),
                ('vendor_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
