# Generated by Django 3.0.8 on 2020-08-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_auto_20200812_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top',
            name='vendor_work_desc',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
