# Generated by Django 3.0.8 on 2020-08-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_auto_20200812_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='top',
            name='Image',
            field=models.ImageField(default='', upload_to='website/images/TOPvendors'),
        ),
    ]
