# Generated by Django 3.0.8 on 2020-08-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_top_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category_title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
