# Generated by Django 3.0.8 on 2020-08-13 15:17

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_service_category_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceContact',
            fields=[
                ('registrant_id', models.AutoField(primary_key=True, serialize=False)),
                ('registrant_name', models.CharField(default='', max_length=50)),
                ('registrant_mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('registrant_query', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
