# Generated by Django 3.0.8 on 2020-08-13 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_servicecontact_regsitrant_interest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecontact',
            old_name='regsitrant_interest',
            new_name='registrant_interest',
        ),
    ]
