# Generated by Django 3.0.8 on 2020-08-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_auto_20200813_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category_title',
            field=models.CharField(default='', max_length=150),
        ),
    ]
