# Generated by Django 3.0.8 on 2020-08-14 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_auto_20200814_1313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
