# Generated by Django 3.0.8 on 2020-08-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('category_title', models.CharField(default='', max_length=150)),
                ('Subcategory', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('service_desc', models.CharField(max_length=120)),
                ('publish_date', models.DateField()),
                ('Image', models.ImageField(default='', upload_to='website/images')),
            ],
        ),
    ]
