# Generated by Django 3.0.8 on 2020-08-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_auto_20200814_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors',
            name='Service_decsription',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
