# Generated by Django 3.0.8 on 2020-08-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_vendors_service_decsription'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors',
            name='Company_Name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
