# Generated by Django 3.0.8 on 2020-08-18 15:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_vendors_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trading',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('address_from', models.CharField(max_length=50)),
                ('address_to', models.CharField(max_length=50)),
                ('zip_code', models.IntegerField(default='')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
    ]
