# Generated by Django 3.0.8 on 2020-08-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_trading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_category', models.CharField(default='', max_length=100)),
                ('market_executive_name', models.CharField(default='', max_length=50)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
            ],
        ),
    ]
