# Generated by Django 3.0.8 on 2020-08-18 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_querycontacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='top',
            name='Busniess_Type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='website.Categories'),
        ),
    ]
