# Generated by Django 3.0.8 on 2020-08-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0050_auto_20200818_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_resume',
            name='copy_resume',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
