# Generated by Django 3.0.8 on 2020-08-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0051_upload_resume_copy_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_resume',
            name='copy_resume',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='upload_resume',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
