# Generated by Django 3.0.8 on 2020-08-18 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0052_auto_20200818_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_resume',
            name='copy_resume',
        ),
    ]
