# Generated by Django 3.0.8 on 2020-08-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0053_remove_upload_resume_copy_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='sub_category_name1',
            new_name='sub_category_name',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='sub_category_name10',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='sub_category_name2',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='sub_category_name3',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='sub_category_name4',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='sub_category_name5',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='sub_category_name6',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='sub_category_name7',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='sub_category_name8',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='sub_category_name9',
        ),
    ]
