# Generated by Django 3.0.8 on 2020-08-20 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0054_auto_20200820_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('subcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Categories')),
            ],
        ),
    ]
