# Generated by Django 3.0.8 on 2020-08-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0063_auto_20200820_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='Subcategory',
            new_name='subcategory',
        ),
    ]
