# Generated by Django 3.0.8 on 2020-08-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0064_auto_20200820_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='subcategory',
            field=models.CharField(default='', max_length=150),
        ),
    ]
