# Generated by Django 3.0.8 on 2020-08-20 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0066_auto_20200820_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.Categories'),
        ),
    ]
