# Generated by Django 3.0.8 on 2020-08-20 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0068_auto_20200820_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingServices',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50)),
                ('category_title', models.CharField(default='', max_length=150)),
                ('price', models.IntegerField(default=0)),
                ('service_desc', models.CharField(max_length=120)),
                ('publish_date', models.DateField()),
                ('Image', models.ImageField(default='', upload_to='website/images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Categories')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Subcategory')),
            ],
        ),
    ]
