# Generated by Django 3.0.8 on 2020-08-20 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0069_trendingservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendingservices',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Categories', unique=True),
        ),
        migrations.AlterField(
            model_name='trendingservices',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Subcategory', unique=True),
        ),
    ]
