# Generated by Django 3.0.8 on 2020-08-20 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0072_auto_20200820_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category_name',
        ),
    ]
