# Generated by Django 3.0.8 on 2020-08-20 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0073_remove_subcategory_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='category_name',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='website.Categories'),
            preserve_default=False,
        ),
    ]
