# Generated by Django 3.0.8 on 2020-08-20 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0076_subcategory_category_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrendingServices',
        ),
    ]
