# Generated by Django 3.0.8 on 2020-08-20 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0077_delete_trendingservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='Busniess_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='website.Categories'),
        ),
    ]
