# Generated by Django 3.0.8 on 2020-08-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0079_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feed_back',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
