# Generated by Django 3.0.8 on 2020-08-22 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0082_auto_20200822_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_sub_category',
            fields=[
                ('subcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_sub_category_name', models.CharField(default='', max_length=50)),
                ('sub_category_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='website.Subcategory')),
            ],
        ),
    ]
