# Generated by Django 3.0.8 on 2020-08-24 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0084_contactviacategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactviacategory',
            name='category',
        ),
        migrations.AddField(
            model_name='contactviacategory',
            name='service_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='website.Sub_sub_category'),
        ),
    ]
