# Generated by Django 3.0.8 on 2020-08-24 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0087_auto_20200824_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactviacategory',
            old_name='service_name',
            new_name='category_name',
        ),
    ]
