# Generated by Django 3.0.8 on 2020-08-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0088_auto_20200824_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactviacategory',
            old_name='sub_service_name',
            new_name='service_name',
        ),
    ]
