# Generated by Django 3.0.8 on 2020-08-24 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0089_auto_20200824_1532'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contactviacategory',
        ),
    ]
