# Generated by Django 3.0.8 on 2020-08-24 15:37

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0090_delete_contactviacategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactviacategory',
            fields=[
                ('registrant_id', models.AutoField(primary_key=True, serialize=False)),
                ('registrant_name', models.CharField(default='', max_length=50)),
                ('registrant_mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('calling_time', models.CharField(default='', max_length=50)),
                ('service_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='website.Subcategory')),
                ('sub_service_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='website.Sub_sub_category')),
            ],
        ),
    ]
