# Generated by Django 3.0.8 on 2020-08-24 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0091_contactviacategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactviacategory',
            name='sub_service_name',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Sub_sub_category'),
        ),
    ]
