# Generated by Django 3.1 on 2020-10-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='punching_out_time',
            field=models.CharField(default='', max_length=50),
        ),
    ]
