# Generated by Django 3.1 on 2020-10-21 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_auto_20201021_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='punch_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 13, 38, 19, 138535)),
        ),
    ]
