# Generated by Django 3.1 on 2021-01-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_auto_20201107_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='punch_in_address',
            field=models.CharField(blank=True, default='', max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='punch_out_address',
            field=models.CharField(blank=True, default='', max_length=225, null=True),
        ),
    ]
