# Generated by Django 3.1 on 2020-10-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_auto_20201021_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='punch_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
