# Generated by Django 3.1 on 2020-10-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_employee_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='education_percentage',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='qualification',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='university',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='year_of_passing',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
