# Generated by Django 3.1 on 2021-01-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_auto_20210122_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='punching_out_time',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
