# Generated by Django 3.1 on 2020-10-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_auto_20201019_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='country',
        ),
        migrations.AlterField(
            model_name='employee',
            name='Mobile_No',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Mobile_No_2',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
