# Generated by Django 3.1 on 2020-10-21 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_auto_20201021_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Employee.employee'),
        ),
    ]
