# Generated by Django 3.1 on 2020-10-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_auto_20201020_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmailID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
