# Generated by Django 3.1 on 2020-10-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_auto_20201021_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
