# Generated by Django 3.1 on 2020-11-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0008_employee_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
