# Generated by Django 3.1 on 2020-10-03 04:24

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(default='', max_length=20)),
                ('Mobile_No', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Mobile_No_2', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Address1', models.CharField(default='', max_length=100)),
                ('Address2', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(choices=[('1', 'Please Select'), ('2', 'Andra Pradesh'), ('3', 'Arunachal Pradesh'), ('4', 'Assam'), ('5', 'Bihar'), ('6', 'Chhattisgarh'), ('7', 'Chandigarh'), ('8', 'Dadar and Nagar Haveli'), ('9', 'Daman and Diu'), ('10', 'Delhi'), ('11', 'Goa'), ('12', 'Gujarat'), ('13', 'Haryana'), ('14', 'Himachal Pradesh'), ('15', 'Jammu and Kashmir'), ('16', 'Jharkhand'), ('17', 'Karnataka'), ('18', 'Kerala'), ('19', 'Lakshadeep'), ('20', 'Madya Pradesh'), ('21', 'Maharashtra'), ('22', 'Manipur'), ('23', 'Meghalaya'), ('24', 'Mizoram'), ('25', 'Nagaland'), ('26', 'Orissa'), ('27', 'Punjab'), ('28', 'Pondicherry'), ('29', 'Rajasthan'), ('30', 'Sikkim'), ('31', 'Tamil Nadu'), ('32', 'Telagana'), ('33', 'Tripura'), ('34', 'Uttaranchal'), ('35', 'Uttar Pradesh'), ('36', 'West Bengal'), ('37', 'Andaman and Nicobar Island')], default='Please Select', max_length=100)),
                ('zipcode', models.IntegerField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('EmailID', models.EmailField(blank=True, max_length=254, null=True)),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
                ('gross_salary', models.BigIntegerField()),
                ('gender', models.CharField(choices=[('1', 'Please Select'), ('2', 'Male'), ('3', 'Female'), ('4', 'Other')], default='Please Select', max_length=100)),
                ('date_of_birth', models.DateField()),
                ('extra_Info', models.TextField(blank=True, max_length=200, null=True)),
                ('Contact_Person', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('employee_is_active', models.BooleanField(default=False)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='dashboard/images/Employee')),
            ],
        ),
        migrations.RenameModel(
            old_name='NewBranch',
            new_name='Branch',
        ),
    ]
