# Generated by Django 3.1 on 2020-10-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='branch_id',
        ),
        migrations.AddField(
            model_name='branch',
            name='id',
            field=models.AutoField(auto_created=True, default='sadas', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
