# Generated by Django 3.1 on 2020-10-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20201003_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='father_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
