# Generated by Django 3.1.2 on 2020-10-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_dailyattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='vendor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='work_description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
