# Generated by Django 3.1 on 2020-10-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_employee_father_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_designation',
            field=models.CharField(default='', max_length=30),
        ),
    ]
