# Generated by Django 3.1 on 2020-10-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_branchreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchreport',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
