# Generated by Django 3.1 on 2020-10-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_employee_employee_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('banner_id', models.AutoField(primary_key=True, serialize=False)),
                ('banner_name', models.CharField(default='', max_length=50)),
                ('banner_img', models.ImageField(upload_to='dashboard/images/banner_1')),
            ],
        ),
        migrations.CreateModel(
            name='Banner2',
            fields=[
                ('banner_id', models.AutoField(primary_key=True, serialize=False)),
                ('banner_name', models.CharField(default='', max_length=50)),
                ('banner_img', models.ImageField(upload_to='dashboard/images/banner_2')),
            ],
        ),
    ]
