# Generated by Django 3.1.2 on 2020-10-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20201014_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='punch_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
