# Generated by Django 3.1 on 2020-10-30 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20201030_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=5000)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.branch')),
            ],
        ),
    ]
