# Generated by Django 3.1 on 2020-10-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_banner_banner2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_img',
            field=models.ImageField(blank=True, null=True, upload_to='dashboard/images/banner_1'),
        ),
    ]
