# Generated by Django 3.1.2 on 2020-10-14 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20201014_1713'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyAttendance',
        ),
    ]
