# Generated by Django 3.1.2 on 2020-10-14 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_delete_dailyattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(choices=[('is_present', 'present'), ('is_absent', 'absent')], default='absent', max_length=20)),
                ('punch_time', models.DateTimeField()),
                ('punch_out_time', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.CharField(blank=True, max_length=50, null=True)),
                ('work_description', models.TextField(blank=True, max_length=1000, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='daily_attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.dailyattendance'),
        ),
    ]
