# Generated by Django 3.1 on 2020-10-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_branchcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_type',
            field=models.CharField(blank=True, choices=[('state', 'state'), ('district', 'district'), ('tehsil', 'tehsil'), ('village', 'village')], max_length=100, null=True),
        ),
    ]
