# Generated by Django 3.1 on 2020-10-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20201003_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_img',
            field=models.ImageField(upload_to='dashboard/images/banner_1'),
        ),
    ]
