# Generated by Django 3.1 on 2020-10-16 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20201016_1033'),
        ('dashboard', '0007_auto_20201014_1806'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='Banner2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='subscription_plan_taken',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='daily_attendance',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='user',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='DailyAttendance',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
