# Generated by Django 3.1 on 2020-10-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_branch_branch_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='Mobile_No',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='Mobile_No_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='landline_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
