# Generated by Django 3.1 on 2020-10-06 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0010_auto_20201006_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='branch_user',
            new_name='branch_user_type',
        ),
        migrations.AddField(
            model_name='branch',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
