# Generated by Django 3.1 on 2020-10-17 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201017_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_vendor_regsitered',
            new_name='is_vendor_registered',
        ),
    ]
