# Generated by Django 3.1 on 2020-10-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='count',
            new_name='otp_count',
        ),
    ]
