# Generated by Django 3.1 on 2020-11-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_customer_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='customer_discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
