# Generated by Django 3.1 on 2020-11-02 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20201102_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='customer_discount',
        ),
    ]
