# Generated by Django 3.1 on 2021-01-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20210105_1537'),
        ('authentication', '0008_auto_20210101_2037'),
    ]

    operations = [
    ]
