# Generated by Django 3.1 on 2020-11-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_user_customer_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
