# Generated by Django 3.1 on 2020-11-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_user_customer_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
